#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 19 17:29:09 2019

@author: cg411
"""

import GW_tools as g 
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt




freqs = np.logspace(-5,1,num=50,base =10)
alpha = 0.138
beta = -221
kappa = 521
gamma =1680
fk = 0.00113

X = -freqs**alpha +beta*freqs*np.sin(kappa*freqs)
sin_f = beta*freqs*np.sin(kappa*freqs)
Y = 1 + np.tanh(gamma*(fk - freqs))
A = 1.80e-44
S = A*freqs**(-7/3)*np.exp(X)*Y

S_nan = np.nan_to_num(S)
om_wd = g.S_to_om(S_nan,freqs)


plt.figure()
plt.semilogx(freqs,X,label='X')
plt.semilogx(freqs,Y,label='Y')
plt.semilogx(freqs,S,label='S')
plt.semilogx(freqs,sin_f,'--',label='Sin')

plt.legend()
plt.figure()
plt.loglog(freqs,np.exp(X),label='expX')




plt.legend()

plt.figure()
plt.loglog(freqs,om_wd)